### ISSUE TITLE
Live streaming transcription 

### ISSUE THREAD

**Issue by idotr7** [SiddhantSadangi/st_deepgram_playground#2] opened 2024-03-25 07:27 UTC
Can you help make it streaming?
When button pressing record with the browser mic

**Comment by SiddhantSadangi** [comment] 2024-03-25 09:19
Duplicate of https://github.com/SiddhantSadangi/st_deepgram_playground/issues/1.

Closing this thread. Please refer to the original issue for discussions and updates.

**Closed as not planned by SiddhantSadangi** 2024-03-25 09:19 UTC
Labels: duplicate
